markdown: rdiscount
permalink: /content/:categories/:title
url: http://www.aliccc.com
description: Joozo.NET
keywords: Joozo.NET
author: Joozo
copyright: copyright
sitedescription: sitedescription
SiteName: SiteName
github: Joozo
safe: true
blogurl: http://joozo.net

exclude: ['old', 'Rakefile']